version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: Scripts/install_dependancies
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: Scripts/start_server
      timeout: 300
      runas: ubuntu
