version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: Scripts/install_dependancies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: Scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: Scripts/restart_server.sh
      timeout: 300
      runas: ubuntu